# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
desc "Description of what the lane does"


before_all do |lane|
	sh("if $CI ;  then echo \"CI - ENABLED\" ; else echo \"CI - DISABLED\" ; fi")
	ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
	ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
  sh("if [ -d ../reports ]; then rm -Rf ../reports; fi")
  sh("if [ -f *.xml ]; then rm -f *.xml; fi")
end


  lane :tests do
  	  run_tests(
	    scheme: "MarvelMVVMTests",
        slack_url: "https://hooks.slack.com/services/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",
        slack_channel: "#marvel-bitrise"
      )
  end
end
