# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :tests do
  	  run_tests(
  	  	workspace: "MarvelMVVM.xcworkspace",
	    	scheme: "MarvelMVVMTests",
        slack_url: "https://love-gpb1386.slack.com/archives/C010N2P832T",
        slack_channel: "#channel",
        slack(
			      pretext: "*ANALYSIS SUCCESSFULLY*",
			      message: "*Author:* #{ commit[:author] } \n*Author email:* #{ commit[:author_email] } \n*Version:* #{ app_version } \n*Branch coverage:* #{ branch_coverage } \n*Code smells:* #{ code_smells } \n*Total tests:* #{ number_of_tests.total } \n*Branch name:* #{ Actions.git_branch.to_s } \n*Commit message:* #{ Actions.last_git_commit_message.to_s }",
			      success: true,
			      slack_url: slack_url,
			      default_payloads: [:test_result]
			   )
      )
  end
end
